### PR TITLE
Changes related to deployment-synchronizer refactoring

### PR DESCRIPTION
**Pull request by manoj-kumara**

### CODE REVIEW

**Comment by manoj-kumara** [comment]
Please hold merging this pull request. I'll update this after reviewing with the team.

**Comment by sagara-gunathunga** [comment]
Hi Manoj, 

What is the status of this fix ? do you want to merge ?

**Comment by prasa7** [comment]
Hi Manoj,
I have done these changes in the following commit[1]. Check whether we need to do any additions. I think this PR has the same changes. Hence no need to merge this I think. Correct me if I'm wrong.

[1] - https://github.com/wso2/carbon-registry/commit/1411b21e698092842d50ca8de7866f0040efd411

Thanks

**Comment by daneshk** [comment]
Closing this PR, since we are not maintaining java8support branch. Please resent the PR to the public branch.

**Pull request closed without merging**
